---
- name: install mysql client and python dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items:
          #- mysql-client
          - build-essential
          - default-libmysqlclient-dev
          - git
          - python
          - python-dev
          - python-setuptools
          - python3-dev
          - python3-pip

- name: pip dependencies
  pip:
     name: 
        - mysqlclient
        - boto3


