---
- name: Install Flask
  pip: name={{ item }} state=present
  with_items:
          - flask
          - flask-mysql

- name: get git repo
  git: repo="https://github.com/mmumshad/simple-webapp.git" dest="/opt/simple-webapp"

- name: print cmd
  #debug: msg="{{ hostvars[groups['db'][0]]["ansible_default_ipv4"]["address"] }}"
  debug: msg="MYSQL_DATABASE_HOST={{ hostvars[groups['db'][0]]["ansible_default_ipv4"]["address"] }} FLASK_APP=/opt/simple-webapp/app.py nohup flask run --host=0.0.0.0 --port=80 &"

- name: start web
  shell: MYSQL_DATABASE_HOST={{ hostvars[groups['db'][0]]["ansible_default_ipv4"]["address"] }} FLASK_APP=/opt/simple-webapp/app.py nohup flask run --host=0.0.0.0 --port=80 &
